export interface Product {
  id: string;
  name: string;
  name_ha?: string;
  category: 'medicines' | 'laptops' | 'perfumes' | 'tech-gadgets';
  subcategory?: 'phones' | 'smartwatches' | 'audio' | 'storage' | 'chargers' | 'headphones' | 'drives';
  subcategory_ha?: string;
  price: number;
  inStock: boolean;
  storeId: string;
  image: string;
  description: string;
  description_ha?: string;
}

export interface Store {
  id: string;
  name: string;
  address: string;
  distance: number;
  hours: string;
  phone: string;
  whatsapp: string;
  lat: number;
  lng: number;
}

export const MOCK_STORES: Store[] = [
  {
    id: 's1',
    name: 'Sokoto Central Pharmacy',
    address: 'Sultan Abubakar Road, Sokoto',
    distance: 0.8,
    hours: '8:00 AM - 10:00 PM',
    phone: '+2348012345678',
    whatsapp: '2348012345678',
    lat: 13.0627,
    lng: 5.2438,
  },
  {
    id: 's2',
    name: 'Giginya Tech Solutions',
    address: 'Giginya Memorial Stadium Road, Sokoto',
    distance: 2.5,
    hours: '9:00 AM - 6:00 PM',
    phone: '+2348022223333',
    whatsapp: '2348022223333',
    lat: 13.0454,
    lng: 5.2322,
  },
  {
    id: 's3',
    name: 'Shehu Shagari Way Fragrances',
    address: 'Shehu Shagari Way, Sokoto',
    distance: 1.2,
    hours: '9:00 AM - 9:00 PM',
    phone: '+2348033334444',
    whatsapp: '2348033334444',
    lat: 13.0565,
    lng: 5.2186,
  },
  {
    id: 's4',
    name: 'Rima River Medicines',
    address: 'Rima Road, Sokoto',
    distance: 0.3,
    hours: '7:00 AM - 8:00 PM',
    phone: '+2348044445555',
    whatsapp: '2348044445555',
    lat: 13.0701,
    lng: 5.2267,
  },
  {
    id: 's5',
    name: 'IbnuBazz Enterprise',
    address: 'Kano Road, Sokoto',
    distance: 1.8,
    hours: '8:30 AM - 7:00 PM',
    phone: '+2348055556666',
    whatsapp: '2348055556666',
    lat: 13.06,
    lng: 5.23,
  },
  {
    id: 's6',
    name: 'TechHub Sokoto',
    address: 'Gusau Road, Sokoto',
    distance: 3.2,
    hours: '9:00 AM - 8:00 PM',
    phone: '+2348066667777',
    whatsapp: '2348066667777',
    lat: 13.05,
    lng: 5.22,
  },
  {
    id: 's7',
    name: 'Sokoto Computer Village',
    address: 'Ahmadu Bello Way, Sokoto',
    distance: 1.5,
    hours: '9:00 AM - 9:00 PM',
    phone: '+2348077778888',
    whatsapp: '2348077778888',
    lat: 13.07,
    lng: 5.24,
  },
  {
    id: 's8',
    name: 'DataLink Computers',
    address: 'Maiduguri Road, Sokoto',
    distance: 2.1,
    hours: '8:00 AM - 6:00 PM',
    phone: '+2348088889999',
    whatsapp: '2348088889999',
    lat: 13.08,
    lng: 5.25,
  },
  {
    id: 's9',
    name: 'CyberZone Sokoto',
    address: 'Umaru Ali Shinkafi Polytechnic Road, Sokoto',
    distance: 4.5,
    hours: '10:00 AM - 10:00 PM',
    phone: '+2348099990000',
    whatsapp: '2348099990000',
    lat: 13.03,
    lng: 5.21,
  },
  {
    id: 's10',
    name: 'GadgetWorld NG',
    address: 'Abdullahi Fodio Road, Sokoto',
    distance: 2.0,
    hours: '9:00 AM - 7:00 PM',
    phone: '+2348100001111',
    whatsapp: '2348100001111',
    lat: 13.055,
    lng: 5.235,
  },
  {
    id: 's11',
    name: 'SmartTech Sokoto',
    address: 'Garba Duba Road, Sokoto',
    distance: 3.0,
    hours: '9:30 AM - 6:30 PM',
    phone: '+2348111112222',
    whatsapp: '2348111112222',
    lat: 13.04,
    lng: 5.225,
  },
  {
    id: 's12',
    name: 'DigiMart Sokoto',
    address: 'Fodio Road, Sokoto',
    distance: 1.9,
    hours: '8:00 AM - 8:00 PM',
    phone: '+2348122223333',
    whatsapp: '2348122223333',
    lat: 13.065,
    lng: 5.238,
  },
  {
    id: 's13',
    name: 'AccessoryHub NG',
    address: 'Kalambaina Road, Sokoto',
    distance: 5.0,
    hours: '10:00 AM - 6:00 PM',
    phone: '+2348133334444',
    whatsapp: '2348133334444',
    lat: 13.02,
    lng: 5.2,
  },
];

const MED_IMG =
  'https://storage.googleapis.com/dala-prod-public-storage/generated-images/67fecc3a-c453-498e-b61a-6036086c93bb/medicine-lonart-7795cb84-1782721174428.webp';
const TECH_IMG =
  'https://storage.googleapis.com/dala-prod-public-storage/generated-images/67fecc3a-c453-498e-b61a-6036086c93bb/laptop-macbook-d6382bc6-1782721174682.webp';
const PERFUME_IMG =
  'https://storage.googleapis.com/dala-prod-public-storage/generated-images/67fecc3a-c453-498e-b61a-6036086c93bb/perfume-oud-6d95d2bc-1782721174658.webp';
const ACCESSORY_IMG = 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/67fecc3a-c453-498e-b61a-6036086c93bb/generic-accessory-7c8b813f-1783060248231.webp';
const CHARGER_IMG = 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/67fecc3a-c453-498e-b61a-6036086c93bb/charger-29aeefb4-1783538635306.webp';
 
export const MOCK_PRODUCTS: Product[] = [
  // Medicines (15)
  {
    id: 'p1',
    name: 'Lonart (Artemether/Lumefantrine)',
    name_ha: 'Maganin Zazzabi (Lonart)',
    category: 'medicines',
    price: 2500,
    inStock: true,
    storeId: 's1',
    description: 'Effective antimalarial treatment for adults.',
    description_ha: 'Ingantaccen maganin zazzabin cizon sauro ga manya.',
    image: MED_IMG,
  },
  {
    id: 'p2',
    name: 'Coartem 80/480',
    name_ha: 'Maganin Zazzabi (Coartem)',
    category: 'medicines',
    price: 3200,
    inStock: true,
    storeId: 's4',
    description: 'High strength antimalarial drug.',
    description_ha: 'Maganin zazzabi mai karfi.',
    image: MED_IMG,
  },
  {
    id: 'p7',
    name: 'Paracetamol 500mg',
    name_ha: 'Maganin Ciwon Kai (Paracetamol)',
    category: 'medicines',
    price: 500,
    inStock: true,
    storeId: 's1',
    description: 'Relief from pain and fever.',
    description_ha: 'Don rage zafi da zazzabi.',
    image: MED_IMG,
  },
  {
    id: 'p8',
    name: 'Amoxicillin Capsules 500mg',
    name_ha: 'Maganin Kumburi (Amoxicillin)',
    category: 'medicines',
    price: 1500,
    inStock: true,
    storeId: 's4',
    description: 'Antibiotic for bacterial infections.',
    description_ha: 'Maganin kwayoyin cuta na antibiotic.',
    image: MED_IMG,
  },
  {
    id: 'p9',
    name: 'Vitamin C Tabs 1000mg',
    name_ha: 'Bitamin C',
    category: 'medicines',
    price: 800,
    inStock: true,
    storeId: 's1',
    description: 'Immune system booster.',
    description_ha: 'Don karfafa garkuwar jiki.',
    image: MED_IMG,
  },
  {
    id: 'p10',
    name: 'Panadol Extra',
    name_ha: 'Panadol Extra',
    category: 'medicines',
    price: 1200,
    inStock: false,
    storeId: 's4',
    description: 'Fast acting pain relief.',
    description_ha: 'Maganin ciwo mai saurin aiki.',
    image: MED_IMG,
  },
  {
    id: 'p11',
    name: 'Emzor Paracetamol 500mg',
    name_ha: 'Emzor Paracetamol',
    category: 'medicines',
    price: 450,
    inStock: true,
    storeId: 's1',
    description: 'Affordable pain relief.',
    description_ha: 'Maganin ciwo mai saukin farashi.',
    image: MED_IMG,
  },
  {
    id: 'p12',
    name: 'Gaviscon Syrup 200ml',
    name_ha: 'Maganin Olsa (Gaviscon)',
    category: 'medicines',
    price: 2800,
    inStock: true,
    storeId: 's4',
    description: 'Relief from heartburn and indigestion.',
    description_ha: 'Don rage zafin kirji da rashin narkewar abinci.',
    image: MED_IMG,
  },
  {
    id: 'p13',
    name: 'Augmentin 625mg',
    name_ha: 'Augmentin',
    category: 'medicines',
    price: 5500,
    inStock: true,
    storeId: 's1',
    description: 'Broad spectrum antibiotic.',
    description_ha: 'Maganin kwayoyin cuta mai karfi.',
    image: MED_IMG,
  },
  {
    id: 'p14',
    name: 'P-Alaxin',
    name_ha: 'P-Alaxin',
    category: 'medicines',
    price: 2200,
    inStock: true,
    storeId: 's4',
    description: 'Trusted antimalarial medication.',
    description_ha: 'Amintaccen maganin zazzabi.',
    image: MED_IMG,
  },
  {
    id: 'p85',
    name: 'Ibuprofen 400mg',
    name_ha: 'Maganin Ciwon Jiki (Ibuprofen)',
    category: 'medicines',
    price: 700,
    inStock: true,
    storeId: 's1',
    description: 'Reduces inflammation and pain.',
    description_ha: 'Yana rage kumburi da ciwo.',
    image: MED_IMG,
  },
  {
    id: 'p86',
    name: 'Loratadine 10mg',
    name_ha: 'Maganin Allergy (Loratadine)',
    category: 'medicines',
    price: 1000,
    inStock: true,
    storeId: 's4',
    description: 'Non-drowsy antihistamine.',
    description_ha: 'Maganin kaikayi da baya sa bacci.',
    image: MED_IMG,
  },
  {
    id: 'p87',
    name: 'Omeprazole 20mg',
    name_ha: 'Maganin Ulcer (Omeprazole)',
    category: 'medicines',
    price: 1800,
    inStock: true,
    storeId: 's1',
    description: 'Treats heartburn, and GERD.',
    description_ha: 'Yana maganin ciwon zuciya da GERD.',
    image: MED_IMG,
  },
  {
    id: 'p88',
    name: 'Salbutamol Inhaler',
    name_ha: 'Maganin Asthma (Salbutamol)',
    category: 'medicines',
    price: 2500,
    inStock: true,
    storeId: 's4',
    description: 'Relief from asthma attacks.',
    description_ha: 'Taimako ga masu cutar fuka.',
    image: MED_IMG,
  },
  {
    id: 'p89',
    name: 'Metformin 500mg',
    name_ha: 'Maganin Ciwon Suga (Metformin)',
    category: 'medicines',
    price: 1200,
    inStock: true,
    storeId: 's1',
    description: 'Manages type 2 diabetes.',
    description_ha: 'Yana kula da ciwon suga na type 2.',
    image: MED_IMG,
  },

  // Laptops (6)
  {
    id: 'p3',
    name: 'MacBook Pro M3 14"',
    name_ha: 'Kwamfutar MacBook Pro M3',
    category: 'laptops',
    price: 1850000,
    inStock: true,
    storeId: 's7',
    description: 'Latest Apple MacBook Pro with M3 Chip.',
    description_ha: 'Sabuwar kwamfutar MacBook Pro mai guntu M3.',
    image: TECH_IMG,
  },
  {
    id: 'p15',
    name: 'HP Pavilion 15',
    name_ha: 'Kwamfutar HP Pavilion 15',
    category: 'laptops',
    price: 450000,
    inStock: true,
    storeId: 's8',
    description: 'Reliable laptop for work and study.',
    description_ha: 'Kwamfuta mai kyau don aiki da karatu.',
    image: TECH_IMG,
  },
  {
    id: 'p16',
    name: 'Dell Latitude 5420',
    name_ha: 'Kwamfutar Dell Latitude 5420',
    category: 'laptops',
    price: 520000,
    inStock: true,
    storeId: 's7',
    description: 'Business class laptop with great durability.',
    description_ha: 'Kwamfutar kasuwanci mai dorewa.',
    image: TECH_IMG,
  },
  {
    id: 'p17',
    name: 'Lenovo ThinkPad X1 Carbon',
    name_ha: 'Kwamfutar Lenovo ThinkPad X1 Carbon',
    category: 'laptops',
    price: 1100000,
    inStock: false,
    storeId: 's6',
    description: 'Ultra-light business flagship.',
    description_ha: 'Kwamfutar kasuwanci mai saukin nauyi.',
    image: TECH_IMG,
  },
  {
    id: 'p19',
    name: 'ASUS ROG Zephyrus G14',
    name_ha: 'Kwamfutar Wasan ASUS ROG Zephyrus G14',
    category: 'laptops',
    price: 1400000,
    inStock: true,
    storeId: 's9',
    description: 'High-performance gaming laptop.',
    description_ha: 'Kwamfutar wasanni mai karfin gaske.',
    image: TECH_IMG,
  },
  {
    id: 'p20',
    name: 'Acer Aspire 5',
    name_ha: 'Kwamfutar Acer Aspire 5',
    category: 'laptops',
    price: 380000,
    inStock: true,
    storeId: 's8',
    description: 'Everyday laptop with modern features.',
    image: TECH_IMG,
  },

  // Tech Gadgets (24)
  {
    id: 'p26',
    name: 'Samsung Galaxy S24 Ultra',
    name_ha: 'Wayar Samsung Galaxy S24 Ultra',
    category: 'tech-gadgets',
    subcategory: 'phones',
    price: 1650000,
    inStock: true,
    storeId: 's10',
    description: 'AI-powered flagship smartphone with S Pen.',
    description_ha: 'Sabuwar wayar Samsung mai amfani da AI da alkalami.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p27',
    name: 'iPhone 15 Pro 256GB',
    name_ha: 'Wayar iPhone 15 Pro',
    category: 'tech-gadgets',
    subcategory: 'phones',
    price: 1550000,
    inStock: true,
    storeId: 's5',
    description: 'Titanium design with A17 Pro chip.',
    description_ha: 'Wayar iPhone mai karfi da kyan gaske.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p28',
    name: 'Apple Watch Series 9',
    name_ha: 'Agogon Apple Series 9',
    category: 'tech-gadgets',
    subcategory: 'smartwatches',
    price: 650000,
    inStock: true,
    storeId: 's11',
    description: 'Advanced health features and faster chip.',
    description_ha: 'Agogon zamani mai lura da lafiya.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p29',
    name: 'AirPods Pro (2nd Gen)',
    name_ha: 'Abin saurare na AirPods Pro',
    category: 'tech-gadgets',
    subcategory: 'audio',
    price: 320000,
    inStock: true,
    storeId: 's13',
    description: 'Active noise cancellation and spatial audio.',
    description_ha: 'Abin saurare mai tace hayaniya.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p30',
    name: 'Sony WH-1000XM5 Headphones',
    name_ha: 'Babban Abin saurare na Sony',
    category: 'tech-gadgets',
    subcategory: 'headphones',
    price: 580000,
    inStock: true,
    storeId: 's12',
    description: 'Industry-leading noise cancellation headphones.',
    description_ha: 'Babban abin saurare mai ingancin gaske.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p31',
    name: 'SanDisk Ultra 64GB Flash Drive',
    name_ha: 'Flash drive na SanDisk 64GB',
    category: 'tech-gadgets',
    subcategory: 'drives',
    price: 8500,
    inStock: true,
    storeId: 's8',
    description: 'High-speed USB 3.0 flash drive.',
    description_ha: 'Abin adana bayanai mai sauri.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p32',
    name: 'Samsung T7 1TB Portable SSD',
    name_ha: 'SSD na Samsung T7 1TB',
    category: 'tech-gadgets',
    subcategory: 'drives',
    price: 145000,
    inStock: true,
    storeId: 's7',
    description: 'Portable external SSD with password protection.',
    description_ha: 'Abin adana bayanai na zamani mai karfi.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p33',
    name: 'WD Elements 2TB External HDD',
    name_ha: 'Hard drive na WD 2TB',
    category: 'tech-gadgets',
    subcategory: 'drives',
    price: 95000,
    inStock: false,
    storeId: 's6',
    description: 'Simple, fast, and portable external storage.',
    description_ha: 'Abin adana bayanai mai girma.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p34',
    name: 'Tecno Camon 30 Premier',
    name_ha: 'Wayar Tecno Camon 30',
    category: 'tech-gadgets',
    subcategory: 'phones',
    price: 550000,
    inStock: true,
    storeId: 's5',
    description: 'Professional photography smartphone.',
    description_ha: 'Wayar Tecno mai kyan hoto.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p35',
    name: 'Infinix Note 40 Pro',
    name_ha: 'Wayar Infinix Note 40',
    category: 'tech-gadgets',
    subcategory: 'phones',
    price: 420000,
    inStock: true,
    storeId: 's10',
    description: 'Fast charging and high-refresh display.',
    description_ha: 'Wayar Infinix mai saurin caji.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p36',
    name: 'Oraimo Watch 4 Plus',
    name_ha: 'Agogon Oraimo Watch 4',
    category: 'tech-gadgets',
    subcategory: 'smartwatches',
    price: 45000,
    inStock: true,
    storeId: 's13',
    description: 'Smartwatch with Bluetooth calling.',
    description_ha: 'Agogon Oraimo mai kiran waya.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p90',
    name: 'Dell 24" Monitor (S2421H)',
    name_ha: 'Monitor na Dell 24"',
    category: 'tech-gadgets',
    price: 150000,
    inStock: true,
    storeId: 's8',
    description: 'FHD monitor with built-in speakers.',
    description_ha: 'FHD monitor mai lasifika.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p91',
    name: 'Anker PowerCore 10000mAh Power Bank',
    name_ha: 'Cajin Waya na Anker 10000mAh',
    category: 'tech-gadgets',
    subcategory: 'chargers',
    price: 25000,
    inStock: true,
    storeId: 's10',
    description: 'Compact and portable power bank.',
    description_ha: 'Karamin caji mai saukin daukewa.',
    image: CHARGER_IMG,
  },
  {
    id: 'p92',
    name: 'Logitech C920 HD Pro Webcam',
    name_ha: 'Kyamarar Yanar Gizo ta Logitech C920',
    category: 'tech-gadgets',
    price: 65000,
    inStock: true,
    storeId: 's9',
    description: 'Full HD 1080p video calling.',
    description_ha: 'Kiran bidiyo na Full HD 1080p.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p93',
    name: 'JBL Flip 6 Bluetooth Speaker',
    name_ha: 'Lasifikar Bluetooth ta JBL Flip 6',
    category: 'tech-gadgets',
    subcategory: 'audio',
    price: 85000,
    inStock: true,
    storeId: 's12',
    description: 'Waterproof portable speaker.',
    description_ha: 'Lasifika mai hana ruwa shiga.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p94',
    name: 'APC 6-Outlet Surge Protector',
    name_ha: 'Kariyar Wutar Lantarki ta APC',
    category: 'tech-gadgets',
    subcategory: 'chargers',
    price: 15000,
    inStock: true,
    storeId: 's6',
    description: 'Protects electronics from power surges.',
    description_ha: 'Yana kare kayan lantarki daga hawan wuta.',
    image: CHARGER_IMG,
  },
  {
    id: 'p95',
    name: 'Bose QuietComfort Earbuds II',
    name_ha: 'Abin Saurare na Bose QC II',
    category: 'tech-gadgets',
    subcategory: 'audio',
    price: 350000,
    inStock: true,
    storeId: 's11',
    description: "World's best noise cancellation.",
    description_ha: 'Mafi kyawun tace hayaniya a duniya.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p96',
    name: 'Blue Yeti USB Microphone',
    name_ha: 'Makirufo na USB ta Blue Yeti',
    category: 'tech-gadgets',
    subcategory: 'audio',
    price: 120000,
    inStock: true,
    storeId: 's9',
    description: 'Professional USB microphone.',
    description_ha: 'Makirufo na USB na kwararru.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p97',
    name: '15-inch Laptop Screen Protector',
    name_ha: 'Kariyar Allon Kwamfuta 15-inch',
    category: 'tech-gadgets',
    price: 5000,
    inStock: true,
    storeId: 's8',
    description: 'Anti-glare screen protector.',
    description_ha: 'Kariyar allo mai hana sheki.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p98',
    name: 'Google Pixel 8a',
    name_ha: 'Wayar Google Pixel 8a',
    category: 'tech-gadgets',
    subcategory: 'phones',
    price: 650000,
    inStock: true,
    storeId: 's5',
    description: 'The helpful phone, engineered by Google.',
    description_ha: 'Waya mai taimako, wacce Google ya kera.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p99',
    name: 'Samsung 27" Odyssey G5 Gaming Monitor',
    name_ha: 'Monitor na Wasan Samsung Odyssey G5 27"',
    category: 'tech-gadgets',
    price: 350000,
    inStock: true,
    storeId: 's9',
    description: 'Curved gaming monitor with 144Hz refresh rate.',
    description_ha: 'Monitor na wasa mai lan\u0199wasa da saurin 144Hz.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p100',
    name: 'Xiaomi 20000mAh Power Bank',
    name_ha: 'Cajin Waya na Xiaomi 20000mAh',
    category: 'tech-gadgets',
    subcategory: 'chargers',
    price: 30000,
    inStock: true,
    storeId: 's10',
    description: 'High capacity power bank with fast charging.',
    description_ha: 'Babban caji mai karfin gaske da saurin caji.',
    image: CHARGER_IMG,
  },
  {
    id: 'p101',
    name: 'Razer Kiyo Webcam',
    name_ha: 'Kyamarar Yanar Gizo ta Razer Kiyo',
    category: 'tech-gadgets',
    price: 80000,
    inStock: false,
    storeId: 's12',
    description: 'Webcam with built-in ring light.',
    description_ha: 'Kyamarar yanar gizo mai hasken zobe.',
    image: ACCESSORY_IMG,
  },
  {
    id: 'p102',
    name: 'Sony SRS-XB100 Bluetooth Speaker',
    name_ha: 'Lasifikar Bluetooth ta Sony SRS-XB100',
    category: 'tech-gadgets',
    subcategory: 'audio',
    price: 55000,
    inStock: true,
    storeId: 's11',
    description: 'Compact waterproof speaker with extra bass.',
    description_ha: 'Karamin lasifika mai hana ruwa da extra bass.',
    image: ACCESSORY_IMG,
  },
  
  // Perfumes (15)
  {
    id: 'p4',
    name: 'Oud Al Sultan',
    name_ha: 'Turaren Oud Al Sultan',
    category: 'perfumes',
    price: 35000,
    inStock: true,
    storeId: 's3',
    description: 'A rich and lasting Arabian fragrance.',
    description_ha: 'Turare mai kauri da kamshi mai dorewa.',
    image: PERFUME_IMG,
  },
  {
    id: 'p5',
    name: 'Dior Sauvage Elixir',
    name_ha: 'Turaren Dior Sauvage Elixir',
    category: 'perfumes',
    price: 150000,
    inStock: true,
    storeId: 's3',
    description: 'A highly concentrated, spicy and fresh scent.',
    description_ha: 'Turare mai karfi da kamshin yaji da sanyi.',
    image: PERFUME_IMG,
  },
  {
    id: 'p6',
    name: 'Baccarat Rouge 540',
    name_ha: 'Turaren Baccarat Rouge 540',
    category: 'perfumes',
    price: 280000,
    inStock: false,
    storeId: 's3',
    description: 'A luminous and intense amber floral fragrance.',
    description_ha: 'Turare mai haske da kauri na amber da fure.',
    image: PERFUME_IMG,
  },
  {
    id: 'p21',
    name: 'Tom Ford Black Orchid',
    name_ha: 'Turaren Tom Ford Black Orchid',
    category: 'perfumes',
    price: 130000,
    inStock: true,
    storeId: 's3',
    description: 'A luxurious and sensual fragrance.',
    description_ha: "Turare mai alfarma da sha'awa.",
    image: PERFUME_IMG,
  },
  {
    id: 'p22',
    name: 'Creed Aventus',
    name_ha: 'Turaren Creed Aventus',
    category: 'perfumes',
    price: 350000,
    inStock: true,
    storeId: 's3',
    description: 'A sophisticated fruity and rich scent.',
    description_ha: "Turare mai kyau na 'ya'jan itace.",
    image: PERFUME_IMG,
  },
  {
    id: 'p23',
    name: 'Armaf Club de Nuit Intense',
    name_ha: 'Turaren Armaf Club de Nuit',
    category: 'perfumes',
    price: 45000,
    inStock: true,
    storeId: 's3',
    description: 'A popular and long-lasting fragrance.',
    description_ha: 'Turare mai farin jini da dorewa.',
    image: PERFUME_IMG,
  },
  {
    id: 'p24',
    name: 'Versace Eros',
    name_ha: 'Turaren Versace Eros',
    category: 'perfumes',
    price: 85000,
    inStock: true,
    storeId: 's3',
    description: 'A bold, fresh, and masculine fragrance.',
    description_ha: 'Turare mai karfi, sanyi, da na maza.',
    image: PERFUME_IMG,
  },
  {
    id: 'p25',
    name: 'Lattafa Asad',
    name_ha: 'Turaren Lattafa Asad',
    category: 'perfumes',
    price: 28000,
    inStock: true,
    storeId: 's3',
    description: 'A warm spicy and amber fragrance.',
    description_ha: 'Turare mai dumin yaji da amber.',
    image: PERFUME_IMG,
  },
  {
    id: 'p103',
    name: 'Chanel Bleu de Chanel',
    name_ha: 'Turaren Chanel Bleu de Chanel',
    category: 'perfumes',
    price: 140000,
    inStock: true,
    storeId: 's3',
    description: 'A woody, aromatic fragrance for the man who defies convention.',
    description_ha: 'Turare mai kamshin itace da na gargajiya ga namiji mai zaman kansa.',
    image: PERFUME_IMG,
  },
  {
    id: 'p104',
    name: 'Paco Rabanne 1 Million',
    name_ha: 'Turaren Paco Rabanne 1 Million',
    category: 'perfumes',
    price: 95000,
    inStock: true,
    storeId: 's3',
    description: 'A warm, spicy scent for men.',
    description_ha: 'Turare mai dumi da yaji na maza.',
    image: PERFUME_IMG,
  },
  {
    id: 'p105',
    name: 'Giorgio Armani Acqua di Gio',
    name_ha: 'Turaren Giorgio Armani Acqua di Gio',
    category: 'perfumes',
    price: 110000,
    inStock: true,
    storeId: 's3',
    description: 'A fresh, aquatic fragrance for men.',
    description_ha: 'Turare mai sanyi da kamshin ruwa na maza.',
    image: PERFUME_IMG,
  },
  {
    id: 'p106',
    name: 'Yves Saint Laurent Y EDP',
    name_ha: 'Turaren Yves Saint Laurent Y EDP',
    category: 'perfumes',
    price: 125000,
    inStock: false,
    storeId: 's3',
    description: 'A bold and woody fragrance for men.',
    description_ha: 'Turare mai karfi da kamshin itace na maza.',
    image: PERFUME_IMG,
  },
  {
    id: 'p107',
    name: 'Prada Luna Rossa Carbon',
    name_ha: 'Turaren Prada Luna Rossa Carbon',
    category: 'perfumes',
    price: 115000,
    inStock: true,
    storeId: 's3',
    description: 'An aromatic fougère fragrance for men.',
    description_ha: 'Turare mai kamshi na fougère na maza.',
    image: PERFUME_IMG,
  },
  {
    id: 'p108',
    name: 'Mancera Cedrat Boise',
    name_ha: 'Turaren Mancera Cedrat Boise',
    category: 'perfumes',
    price: 98000,
    inStock: true,
    storeId: 's3',
    description: 'A citrus aromatic fragrance for women and men.',
    description_ha: 'Turare mai kamshin citrus na mata da maza.',
    image: PERFUME_IMG,
  },
  {
    id: 'p109',
    name: 'Nishane Hacivat',
    name_ha: 'Turaren Nishane Hacivat',
    category: 'perfumes',
    price: 180000,
    inStock: true,
    storeId: 's3',
    description: 'A chypre fragrance for women and men.',
    description_ha: 'Turare na chypre na mata da maza.',
    image: PERFUME_IMG,
  },
];

export const SMART_SEARCH_MAP: Record<string, string[]> = {
  malaria: ['Lonart', 'Coartem', 'Artemether', 'P-Alaxin'],
  zazzabi: ['Lonart', 'Coartem', 'Artemether', 'P-Alaxin'],
  drug: [
    'Lonart',
    'Coartem',
    'Paracetamol',
    'Amoxicillin',
    'Vitamin C',
    'Panadol',
    'Emzor',
    'Gaviscon',
    'Augmentin',
    'P-Alaxin',
    'Ibuprofen',
    'Loratadine',
    'Omeprazole',
    'Salbutamol',
    'Metformin',
  ],
  medicine: [
    'Lonart',
    'Coartem',
    'Paracetamol',
    'Amoxicillin',
    'Vitamin C',
    'Panadol',
    'Emzor',
    'Gaviscon',
    'Augmentin',
    'P-Alaxin',
    'Ibuprofen',
    'Loratadine',
    'Omeprazole',
    'Salbutamol',
    'Metformin',
  ],
  magani: [
    'Lonart',
    'Coartem',
    'Paracetamol',
    'Amoxicillin',
    'Vitamin C',
    'Panadol',
    'Emzor',
    'Gaviscon',
    'Augmentin',
    'P-Alaxin',
    'Ibuprofen',
    'Loratadine',
    'Om_eprazole',
    'Salbutamol',
    'Metformin',
  ],
  ciwo: ['Paracetamol', 'Panadol', 'Emzor', 'Ibuprofen'],
  laptop: ['MacBook', 'HP', 'Dell', 'Lenovo', 'ASUS', 'Acer'],
  computer: ['MacBook', 'HP', 'Dell', 'Lenovo', 'ASUS', 'Acer'],
  kwamfuta: ['MacBook', 'HP', 'Dell', 'Lenovo', 'ASUS', 'Acer'],
  perfume: [
    'Oud',
    'Sauvage',
    'Baccarat',
    'Black Orchid',
    'Creed',
    'Sultan',
    'Armaf',
    'Versace',
    'Lattafa',
    'Chanel',
    'Paco Rabanne',
    'Giorgio Armani',
    'Yves Saint Laurent',
    'Prada',
    'Mancera',
    'Nishane',
  ],
  turare: [
    'Oud',
    'Sauvage',
    'Baccarat',
    'Black Orchid',
    'Creed',
    'Sultan',
    'Armaf',
    'Versace',
    'Lattafa',
    'Chanel',
    'Paco Rabanne',
    'Giorgio Armani',
    'Yves Saint Laurent',
    'Prada',
    'Mancera',
    'Nishane',
  ],
  phone: ['Samsung', 'iPhone', 'Tecno', 'Infinix', 'Google Pixel'],
  waya: ['Samsung', 'iPhone', 'Tecno', 'Infinix', 'Google Pixel'],
  wayoyi: ['Samsung', 'iPhone', 'Tecno', 'Infinix', 'Google Pixel'],
  tarho: ['Samsung', 'iPhone', 'Tecno', 'Infinix', 'Google Pixel'],
  watch: ['Apple Watch', 'Oraimo Watch'],
  ago: ['Apple Watch', 'Oraimo Watch'],
  agogo: ['Apple Watch', 'Oraimo Watch'],
  agogona: ['Apple Watch', 'Oraimo Watch'],
  earbuds: ['AirPods', 'Bose'],
  headphone: ['Sony'],
  saurare: ['AirPods', 'Sony', 'Bose', 'JBL'],
  audio: ['AirPods', 'Sony', 'Bose', 'JBL'],
  sauti: ['AirPods', 'Sony', 'Bose', 'JBL'],
  flash: ['SanDisk'],
  gadget: ['Samsung', 'iPhone', 'Apple Watch', 'AirPods', 'Sony', 'SanDisk', 'Samsung', 'Anker', 'Xiaomi'],
  'tech gadget': ['Samsung', 'iPhone', 'Apple Watch', 'AirPods', 'Sony', 'SanDisk', 'Samsung', 'Anker', 'Xiaomi'],
  lantarki: ['Samsung', 'iPhone', 'Apple Watch', 'AirPods', 'Sony', 'SanDisk', 'Samsung', 'Anker', 'Xiaomi'],
  kayan: ['Samsung', 'iPhone', 'Apple Watch', 'AirPods', 'Sony', 'SanDisk', 'Samsung', 'Anker', 'Xiaomi'],
  ssd: ['Samsung'],
  'hard drive': ['WD'],
  'abin adana': ['SanDisk', 'Samsung', 'WD'],
  'abin saurare': ['AirPods', 'Sony', 'Bose', 'JBL'],
  "ma'ajiya": ['SanDisk', 'Samsung', 'WD'],
  ajiya: ['SanDisk', 'Samsung', 'WD'],
  monitor: ['Dell', 'Samsung'],
  'power bank': ['Anker', 'Xiaomi'],
  caji: ['Anker', 'Xiaomi'],
  webcam: ['Logitech', 'Razer'],
  speaker: ['JBL', 'Sony'],
  lasifika: ['JBL', 'Sony'],
  'surge protector': ['APC'],
  kariya: ['APC'],
  microphone: ['Blue Yeti'],
  makirufo: ['Blue Yeti'],
  'screen protector': [],
  airpods: ['AirPods'],
  galaxy: ['Samsung'],
  iphone: ['iPhone'],
  tecno: ['Tecno'],
  infinix: ['Infinix'],
  pixel: ['Google Pixel'],
  oraimo: ['Oraimo Watch'],
  jbl: ['JBL'],
  bose: ['Bose'],
  sony: ['Sony'],
  sandisk: ['SanDisk'],
  anker: ['Anker'],
  xiaomi: ['Xiaomi'],
  logitech: ['Logitech'],
  razer: ['Razer'],
  apc: ['APC'],
  'blue yeti': ['Blue Yeti'],
  apple: ['Apple Watch', 'AirPods', 'iPhone', 'MacBook'],
  samsung: ['Samsung'],
  nvme: ['Samsung'],
  'usb drive': ['SanDisk'],
  hdd: ['WD'],
};